version: '3.3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always
    volumes: 
      - mongodb:/data/db

  huggingchat:
    build: 
      context: ..
    ports:
      - '3000:3000'

volumes:
  mongodb: